# Generated by Django 5.1.6 on 2025-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_portfolio_application_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cv/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
