# Generated by Django 5.1.6 on 2025-04-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='image',
        ),
    ]
