# Generated by Django 5.2 on 2025-04-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Job Update', 'Job Update'), ('Connection Request', 'Connection Request')], default='Application', max_length=50),
        ),
    ]
