# Generated by Django 5.2 on 2025-04-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cv_image'),
        ('app', '0006_alter_portfolio_user_id'),
    ]

    operations = [
    ]
