# Generated by Django 5.1.6 on 2025-05-01 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_course_coursevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jobposting'),
        ),
    ]
