# Generated by Django 5.2 on 2025-04-30 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='working_hours',
            field=models.CharField(default='40 hours/week', max_length=100),
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='app.jobposting')),
            ],
        ),
    ]
