# Generated by Django 5.2 on 2025-05-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_premiumsubscription'),
        ('app', '0010_message'),
    ]

    operations = [
    ]
