# Generated by Django 5.2 on 2025-05-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_jobposting_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jobposting'),
        ),
    ]
