# Generated by Django 5.2 on 2025-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='working_hours',
            field=models.IntegerField(default='40 hours/week', max_length=100),
        ),
    ]
