# Generated by Django 5.2 on 2025-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_jobposting_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='working_hours',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
