# Generated by Django 5.2 on 2025-05-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_message'),
        ('app', '0014_alter_jobposting_working_hours'),
    ]

    operations = [
    ]
