# Generated by Django 5.2 on 2025-05-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20250503_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_by',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='working_hours',
            field=models.IntegerField(default=0),
        ),
    ]
